### ISSUE TITLE
Displaying values within the stacked bars

### ISSUE THREAD

**Issue by hnhegde** [ricardodorosario/react-horizontal-stacked-bar-chart#3]
Hello,
`ShowText[Up | Down]` options display the title and value together, either within the bars, above them or below them. How can I make the title appear on the top and the value inside the bars? 
Kindly advise,

Thanks,
Harsha

**Comment by ricardodorosario** [comment]
Hi Harsha,

I didn't make the component to be displayed like this.
You could try not pass the 'name' param and pass the 'showText' param. It does the value show inside the bars without the title like this:

`<HSBar
        showText
        data={[
          { value: 10000, description: "10.000" },
          { value: 5000, description: "5.000" },
          { value: 3000, description: "3.000" }
        ]}
      />`

Even so I will try to change the component accord your case.
